name: CI
Turn dryer noise off
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |grow solid crystal and realize you do have payment in the bak
        
echo Add other actions to build,
        echo test, and deploy your project.
