name: CI
Turn dryer noise off
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |see that you was paid your wages to your business to use in good works
        echo Add other actions to build,
        echo test, and deploy your project. 
Iras construction groups has employed you as a representative with 6 months sign on bonus and 10,000
US dollars monthly allowance plus comission. Available immediately
